In [38]:
import numpy as np

## 1.
Create a NumPy vector called `primes` that consists of the first 8 prime numbers. (You can simply type in the values, nothing fancy needed to compute them.)

In [5]:
primes = None

primes = np.array([2, 3, 5, 7, 11, 13, 17, 19])

print(primes)

[ 2  3  5  7 11 13 17 19]


In [8]:
# TESTS
assert type(primes) == np.ndarray
assert primes.shape == (8,)
assert np.sum(primes) == 77
print("OK")

OK


In [7]:
# Intentionally blank--do not delete

## 2. 
Create a NumPy vector called `squares` that consists of the values [1, 4, 9, 16, …, 1521, 1600].

In [10]:
squares = None

squares = np.array([i**2 for i in range(1, 41)])

print(squares)

[   1    4    9   16   25   36   49   64   81  100  121  144  169  196
  225  256  289  324  361  400  441  484  529  576  625  676  729  784
  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600]


In [11]:
# TESTS
assert type(squares) == np.ndarray
assert squares.shape == (40,)
assert np.sum(squares) == 22140
print("OK")

OK


In [ ]:
# Intentionally blank--do not delete

## 3.
Create a matrix `C` with 27 rows and 44 columns having all entries equal to 5.2.

In [12]:
C = None

C = np.full((27, 44), 5.2)

print("upper left corner:")
print(C[:4, :6])

upper left corner:
[[5.2 5.2 5.2 5.2 5.2 5.2]
 [5.2 5.2 5.2 5.2 5.2 5.2]
 [5.2 5.2 5.2 5.2 5.2 5.2]
 [5.2 5.2 5.2 5.2 5.2 5.2]]


In [13]:
# TESTS
assert type(C) == np.ndarray
assert C.shape == (27, 44)
print("OK")

OK


In [14]:
# Intentionally blank--do not delete

# 4.

Here is a matrix `R`.

In [15]:
R = np.reshape(range(0, 30), (5, 6))
R

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

Use a **single numpy slice command** to extract this submatrix:

$$
S = 
\begin{bmatrix}
2 & 3 & 4 \\ 14 & 15 & 16 \\ 26 & 27 & 28
\end{bmatrix}
$$

In [16]:
S = None
S = R[0::2, 2:5]

print("your slice:")
print(S)

your slice:
[[ 2  3  4]
 [14 15 16]
 [26 27 28]]


In [17]:
# TESTS
assert np.all( S == np.array([[2, 3, 4], [14, 15, 16], [26, 27, 28]]) )
print("OK")

OK


## 5.
Write a function `row_col_mean` that accepts a matrix as input and returns two vectors: the mean value in every row and the mean value in every column. So, for example, the input
$$
\begin{bmatrix}
2 & -1 & 2 \\ -3 & 1 & 2
\end{bmatrix}
$$
would produce the outputs $[1, \: 0]$ and $[-0.5,\: 0,\: 2]$.

In [36]:
def row_col_mean(A):
    row_mean = np.mean(A, axis=1)  
    col_mean = np.mean(A, axis=0)
    return row_mean, col_mean

In [37]:
# TESTS
B = np.array([[1, 3, 4],[5, 0, 2]])
assert np.all( np.isclose(row_col_mean(B)[0], np.array([2.6666667, 2.3333333])) )
assert np.all( np.isclose(row_col_mean(B)[1], np.array([3, 1.5, 3])) )
print("OK")

OK


In [ ]:
# Intentionally blank--do not delete